--查询每位同学不低于自己平均成绩的所有课程并输出该元组的学号、课程号、成绩
USE JXGL
GO
	SELECT SNO,CNO,GRADE
	FROM SC$ SC1
	WHERE GRADE>=
		(SELECT AVG(GRADE)
		 FROM SC$ SC2
		 WHERE SC1.SNO=SC2.SNO)
GO
--查询选修了C003的学生姓名
USE JXGL
GO
	SELECT SNAME
	FROM S$
	WHERE EXISTS
		(SELECT *
		 FROM SC$
		 WHERE S$.SNO=SC$.SNO AND CNO='C003')
GO