--内连接的应用
--查询课程号和平均成绩
USE JXGL
GO
	SELECT CNO,ROUND(AVG(GRADE),2) AS AVERAGE
	FROM S$,SC$
	WHERE S$.SNO=SC$.SNO AND SDPET='CS'
	GROUP BY CNO
GO

--查询选修c007课程成绩高于学号为100007的同学成绩的所有学生元组，并按成绩排序
USE JXGL
GO
	SELECT SC1$.SNO,SC1$.CNO,SC1$.GRADE
	FROM SC$ SC1$,SC$ SC2$
	WHERE SC1$.CNO='C007' AND SC1$.GRADE>SC2$.GRADE AND SC2$.SNO=100007 AND SC2$.CNO='C007'
	ORDER BY GRADE DESC
GO